services:
  postgres:
    image: postgres:17
    container_name: schema_drift_postgres
    restart: always

    environment:
      POSTGRES_USER: schema_user
      POSTGRES_PASSWORD: schema_password
      POSTGRES_DB: schema_drift_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: