# A generic, single database configuration.

[alembic]

script_location = %(here)s/alembic

prepend_sys_path = .

path_separator = os

sqlalchemy.url = postgresql://schema_user:schema_password@localhost:5433/schema_drift_db


[post_write_hooks]


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic


[logger_root]
level = WARNING
handlers = console
qualname =


[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine


[logger_alembic]
level = INFO
handlers =
qualname = alembic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S



#Alembic is basically used to migrate data from application to postegreSQL. 
#For example, if i have id and name as columns in my python program, postgre will also have id and name
# if i add id, name and then source, without alembic, the changes wont be reflected on postgre due to lack of migration.
#it does this migration by comparing first and then generating a migration script. It is used to manage database schema changes over time.
#then we run the 'head' command to make the changes to postgre. 


#in a nutshell, SQLAlchemy models describe your database structure and let Python interact with the database;
 Base.metadata holds those model/table definitions on the Python side; 
 Alembic uses that structure to detect/generate database schema changes and then applies those 
 changes to PostgreSQL through migrations.

 #base.metadata is an object 